package commands;


public enum CommandType {
    SETNICK, UPDATELOBBYLIST, GETCATEGORIES, SENDCATEGORIES, GETLOBBYLIST, UPDATENICK, UPDATEROOM, CREATEROOM, PLAYERLEAVE, GETROOM, UPDATEROOMNAME, PLAYERREADY, PLAYERNOTREADY, UPDATEROOMPLAYERLIST, PLAYERJOIN, SENDMESSAGE, PLAYERSENDMESSAGE
}
